In [1]:
#!/usr/bin/env python3

import numpy as np

In [2]:
class ActiveFunctions:
    """
    A base class of activation functions.
    """
    def at(self, rawValues):
        return rawValues
    
    def gradientAt(self, rawValues):
        return 1.0


In [3]:
class ReLu(ActiveFunctions):
    """
    ReLu activation function.
    """
    def at(self, rawValues):
        if type(rawValues) != np.ndarray:
            return rawValues if rawValues > 0.0 else 0.0
        
        output = np.zeros(rawValues.shape)
        for idx, value in enumerate(rawValues):
            output[idx] = value if value > 0.0 else 0.0
        return output
    
    def gradientAt(self, rawValues):
        if type(rawValues) != np.ndarray:
            return 1.0 if rawValues > 0.0 else 0.0
        
        output = np.zeros(rawValues.shape)
        for idx, value in enumerate(rawValues):
            output[idx] = 1.0 if value > 0.0 else 0.0
        return output

In [4]:
class Softmax(ActiveFunctions):
    """
    Softmax activation function.
    """
    def at(self, rawValues):
        if type(rawValues) is not np.ndarray: 
            raise TypeError('<Usage> Softmax.at(vars) where type vars should be numpy.ndarrya!')
        
        rawValues = rawValues.ravel()
        maxValue = max(rawValues)
        rawValues -= maxValue
        output = np.zeros(rawValues.shape)
        for idx, value in enumerate(rawValues):
            output[idx] = np.exp(value) / sum(np.exp(rawValues))
            
        return output
    
    def gradientAt(self, rawValues):
        if type(rawValues) is not np.ndarray: 
            raise TypeError('<Usage> Softmax.at(vars) where type vars should be numpy.ndarrya!')
            
        rawValues = rawValues.ravel()
        maxValue = max(rawValues)
        rawValues -= maxValue    
        
        output = np.zeros(rawValues.shape)
        for idx, value in enumerate(rawValues):
            p = np.exp(value) / sum(np.exp(rawValues))
            output[idx] = p * (1 - p)
        return output

In [5]:
## --------- TESTING --------

if __name__ =='__main__':
    # --- Testing ReLu:
    relu = ReLu()
    testData = np.array([1.0, 100.0, -50.0, 7.56])
    print(relu.at(testData))
    print(relu.gradientAt(testData))
    
    # --- Testing Softmax:
    softmax = Softmax()
    testData = np.array([3, 1, -3])
    print(softmax.at(testData))
    print(softmax.gradientAt(testData))

[  1.   100.     0.     7.56]
[1. 1. 0. 1.]
[0.87887824 0.11894324 0.00217852]
[0.10645128 0.10479574 0.00217378]


0.001996